SELECT NAME FROM CITY WHERE POPULATION>120000 AND COUNTRYCODE='USA';
SELECT * FROM CITY WHERE POPULATION>100000 AND COUNTRYCODE = 'USA';
select * from CITY;
select * from CITY where ID=1661;
select * from CITY where COUNTRYCODE ='JPN';
select NAME from CITY where COUNTRYCODE='JPN';
